package X34.Core;

import X34.Processors.X34RetrievalProcessor;
import com.sun.istack.internal.NotNull;
import core.CoreUtil.IOTools;

import java.io.File;
import java.io.IOException;
import java.io.Serializable;
import java.net.URL;

/**
 * Stores hash and source data for images stored in the {@link X34Index} class.
 */
public class X34Image implements Serializable
{
    public URL source;
    public String tag;
    // Uses a 32-character (16-byte) insecure cryptographic hash generated by either the image server or the client during download
    // to ensure image uniqueness
    public byte[] hash;

    public X34Image(@NotNull URL source, String tag, byte[] hash)
    {
        if(source == null) throw new IllegalArgumentException("Source cannot be null.");

        this.source = source;
        this.tag = tag == null ? "" : tag;
        this.hash = hash == null ? new byte[16] : hash;
    }

    /**
     * Writes the remote image data represented by this object to a file on the local drive.
     * @param parent the directory in which to place the new file
     * @param overwriteExisting set this to true if an attempt should be made to overwrite existing files with the same name as the remote file
     * @param processor the {@link X34RetrievalProcessor} that this image was sourced from
     * @return true if the file write was successful, false if otherwise
     * @throws IOException if a critical error was encountered during the I/O process
     */
    public boolean writeToFile(@NotNull File parent, boolean overwriteExisting, X34RetrievalProcessor processor) throws IOException
    {
        if(parent == null) throw new IllegalArgumentException("Parent directory cannot be null");
        if(source == null) throw new IOException("Source URI is invalid");

        File f = new File(parent, processor.getFilenameFromURL(this.source));

        IOTools.getFileFromURL(this.source.toString(), f, overwriteExisting);
        return f.exists() && f.getName().equals(processor.getFilenameFromURL(this.source));
    }

    /**
     * Verifies the checksum of this object against the remote copy of its linked image.
     * Verification is done using the MD5 cryptographic hash, and is not secure.
     * @return true if the data passed verification, false otherwise
     */
    public boolean verifyIntegrity()
    {
        if(hash == null || hash.length == 0 || source == null) throw new IllegalArgumentException("Invalid hash data or source URI");

        //todo finish
        return false;
    }
}
